[workspace]
package.homepage = "https://candronikos.com/projects/haystack-rust/"
package.repository = "https://github.com/candronikos/haystack"
members = [
    "haystack-types",
    "haystack-client",
]

resolver = "2"