[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH gcc-multilib g++-multilib libc6:$CROSS_DEB_ARCH"
]

[target.i686-unknown-linux-gnu]
linker = "i686-linux-gnu-gcc"
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH gcc-multilib g++-multilib libc6:$CROSS_DEB_ARCH"
]