[package]
name = "haystack-client"
version = "0.1.0"
authors = ["Christopher Andronikos <naxos.holdings@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tokio]
version = "0.2.21"
features = ["macros","sync"]

[dependencies]
futures = "0.3"
scram = "0.5.0"
nom = "6.0.0-alpha1"
url = "2.1.1"
base64 = "0.12.1"
reqwest = { version = "0.10", features = ["blocking"] }

[dev-dependencies]
rstest = { git = "https://github.com/la10736/rstest" }
lazy_static = "1.4.0"