name: Build for macOS (aarch64 and x86_64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          brew install openssl pkg-config
        shell: bash

      # Extract version from Cargo.toml
      - name: Get haystack-client version
        id: get-version
        run: |
          VERSION=$(cargo metadata -q --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "haystack-client") | .version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      # Add Rust target
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}
        shell: bash

      # Build project
      - name: Build project
        run: cargo build --release --target ${{ matrix.target }} -p haystack-client
        shell: bash

      # Upload release binary
      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: haystack-client-v${{ env.VERSION }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/haystack-client