name: Built for Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Set environment variables
        run: echo "OPENSSL_DIR=/usr/lib/ssl" >> $GITHUB_ENV

      - name: Build project
        run: cargo build --release

      - name: Upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: release-binary
          path: target/release/