name: Built for Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Set environment variables
        run: |
          echo "OPENSSL_DIR=/usr/lib/ssl" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build project
        run: cargo build --release -p haystack-client

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: haystack-client
          path: target/release/